### ISSUE TITLE
Implement external annotations mechanism

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1251]
All anotations will be stored in separate yaml files with file per namespace. Format is following:
```
somemethod:
  returns: Foo::Bar
  method: yes
  deprecated: yes
someothermethod:
  returns: Foo::Bar::Baz
  method: no
  deprecated: no
```
Or with injections on each line: 
```
somethirdmethod:
  returns Bar::Baz
  method
  deprected
someforthmethod:
  returns Bar::Bar
  method
  deprected
```

We'll have 3 roots with yaml files:
1. Provided with plugin 
2. Application-level annotations of installed modules
3. Project-level annotations of installed/written modules

- [ ] Three files roots
- [x] Namespace annotation
- [ ] sub names highlighting
- [ ] sub to real sub reference
- [ ] gutter navigation to annotation
- [ ] intention to annotate package/sub
- [ ] duplicate same level annotations inspection
- [ ] gutter naviagation between annotations levels
- [ ] watch if annotations path been changed/renamed
