### ISSUE TITLE
Annotations for __DATA__ section

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2486]
### Discussed in https://github.com/Camelcade/Perl5-IDEA/discussions/2485

<div type='discussions-op-text'>

<sup>Originally posted by **fkoyer** April 19, 2022</sup>
Would it be possible to annotate the \_\_DATA__ section so that the IDE formats it correctly? For example, if I'm storing YAML in the \_\_DATA__ section I would like to do something like this:

```
#@inject YAML
__DATA__
config:
  db:
    host: 127.0.0.1
    user: admin
    pass: top_secret_password
    name: db1
  mailer:
    host: smtp.example.com
    user: support@example.com
    pass: my_email_password
    port: 587
```

This currently works for here-docs but not for the \_\_DATA__ section. I've also seen people store Perl code in the \_\_DATA__ section and pull it in with `eval`. In this case it would nice if we could annotate it with `#@inject PERL5`.

Thanks
Kent</div>
